### ISSUE TITLE
Dependency grr no longer building + removed from CRAN

### ISSUE THREAD

**Issue by halhen** [quadbiolab/Pando#80]
The dependency `grr` has been [removed from CRAN from issues not being corrected on time](https://cran.r-project.org/web/packages/grr/index.html).

Trying to install `grr` in our recent builds on R4.6 gives the error message below. `grr` seems to be an inactive project, so there might not be much hope for it to be fixed upstream.

```
grr.cpp: In function ‘SEXPREC* sortcpp(SEXP)’:
grr.cpp:43:17: error: ‘STRING_PTR’ was not declared in this scope; did you mean ‘STRING_PTR_RO’?
   43 |       std::sort(STRING_PTR(x), STRING_PTR(x) + LENGTH(x), cmp_char);
      |                 ^~~~~~~~~~
      |                 STRING_PTR_RO
grr.cpp: In function ‘void internalOrder(int*, SEXP)’:
grr.cpp:116:20: error: ‘STRING_PTR’ was not declared in this scope; did you mean ‘STRING_PTR_RO’?
  116 |     SEXP* start = &STRING_PTR(x)[0];
      |                    ^~~~~~~~~~
      |                    STRING_PTR_RO
grr.cpp: In function ‘SEXPREC* matches(SEXP, SEXP)’:
grr.cpp:283:21: error: ‘STRING_PTR’ was not declared in this scope; did you mean ‘STRING_PTR_RO’?
  283 |     SEXP* astart = &STRING_PTR(a)[0];
      |                     ^~~~~~~~~~
      |                     STRING_PTR_RO
```

You might need to consider moving away from this dependency
